name: chatboy_voice
description: Aplicación móvil para interactuar con ChatBoy IA usando voz y texto.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.2
  speech_to_text: ^6.5.1
  flutter_tts: ^3.6.3
  just_audio: ^0.9.36
  permission_handler: ^11.0.1
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
